astocks/urls.py
from django.urls import re_path
from .view import pick_views,limitup_views

urlpatterns = [ 
    re_path(r'^$', pick_views.StockChooseListView.as_view(), name='home'),
    re_path(r'^edit_pick/(?P<id>\d+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick'), 
    re_path(r'^delete_pick/(?P<id>\d+)/$', pick_views.DeleteStockChooseView.as_view(), name='delete_pick'), 
    re_path(r'^edit_pick/(?P<id>\d+)/(?P<by>[a-z]+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick_by_date'), 
    re_path(r'^delete_pick/(?P<id>\d+)/(?P<by>[a-z]+)/$', pick_views.DeleteStockChooseByDateView.as_view(), name='delete_pick_by_date'), 
    re_path(r'^edit_pick/(?P<id>\d+)/(?P<bytype>\d+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick_by_type'), 
    re_path(r'^delete_pick/(?P<id>\d+)/(?P<bytype>\d+)/$', pick_views.DeleteStockChooseByTypeView.as_view(), name='delete_pick_by_type'), 
    re_path(r'^edit_pick/(?P<id>\d+)/(?P<byboard>\d+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick_by_board'), 
    re_path(r'^delete_pick/(?P<id>\d+)/(?P<byboard>\d+)/$', pick_views.DeleteStockChooseByBoardView.as_view(), name='delete_pick_by_board'), 
    re_path(r'^choose_date/$', pick_views.byDateListView,name='choose_date'),  
    re_path(r'^choose_type/$', pick_views.byTypeListView,name='choose_type'), 
    re_path(r'^choose_board/$', pick_views.byBoardListView,name='choose_board'),   
    re_path(r'^choose_detail/(?P<name>.+)/$', pick_views.choose_detail,name='choose_detail'), 
    re_path(r'^limitup/$', limitup_views.StockChooseListView.as_view(), name='limitup'),
    re_path(r'^edit_limitup/(?P<id>\d+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/$', limitup_views.DeleteStockChooseView.as_view(), name='delete_limitup'), 
    re_path(r'^edit_limitup/(?P<id>\d+)/(?P<by>[a-z]+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup_by_date'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/(?P<by>[a-z]+)/$', limitup_views.DeleteStockChooseByDateView.as_view(), name='delete_limitup_by_date'), 
    re_path(r'^edit_limitup/(?P<id>\d+)/(?P<bytype>\d+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup_by_type'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/(?P<bytype>\d+)/$', limitup_views.DeleteStockChooseByTypeView.as_view(), name='delete_limitup_by_type'), 
    re_path(r'^edit_limitup/(?P<id>\d+)/(?P<byboard>\d+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup_by_board'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/(?P<byboard>\d+)/$', limitup_views.DeleteStockChooseByBoardView.as_view(), name='delete_limitup_by_board'), 
    re_path(r'^limitup_date/$', limitup_views.byDateListView,name='limitup_date'),
    re_path(r'^limitup_type/$', limitup_views.byTypeListView,name='limitup_type'),
    re_path(r'^limitup_board/$', limitup_views.byBoardListView,name='limitup_board'),
    re_path(r'^limitup_detail/(?P<name>.+)/$', limitup_views.limitup_detail,name='limitup_detail'), 
]

boards/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [ 
    re_path(r'^$', views.BoardListView.as_view(), name='home'),
    re_path(r'^(?P<pk>\d+)/types/(?P<type_pk>\d+)/$', views.ByTypeBoardListView.as_view(), name='type_boards'),
    re_path(r'^(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    re_path(r'^(?P<name>.+)/stocks/$', views.StockListView.as_view(), name='board_stocks'),
    re_path(r'^(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    re_path(r'^(?P<board_name>.+)/stocks/(?P<stock_name>.+)/$', views.stock_detail, name='stock_detail'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/edit/$',
        views.TopicUpdateView.as_view(), name='edit_topic'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),
    path('query', views.query, name='query'),
    path('blockquery', views.blockquery, name='blockquery'),
    path('blockget', views.blockget, name='blockget'),
    path('singleget', views.singleget, name='singleget'),
    path('dtype_boards', views.ByDTypeBoardListView.as_view(), name='dtype_boards'),
]

pick/urls.py
from django.urls import re_path,path
from . import views as pick_views
from .view import pick_views as select_views

urlpatterns = [ 
    re_path(r'^$', pick_views.home, name='home'),
    path('query/', pick_views.query,name='query'),  
    path('jquery/', pick_views.jquery,name='jquery'), 
    path('pe_dayadd/', pick_views.pe_dayadd,name='pe_dayadd'), 
    path('dayadd/', pick_views.dayadd,name='dayadd'), 
    path('blockadd/', pick_views.blockadd,name='blockadd'), 
    path('indexadd/', pick_views.indexadd,name='indexadd'), 
    path('blockdayadd/', pick_views.blockdayadd,name='blockdayadd'), 
    path('dayout/', pick_views.dayout,name='dayout'), 
    path('inflow/', pick_views.inflow,name='inflow'),
    path('binflow/', pick_views.binflow,name='binflow'),
    path('inflow_single/', pick_views.inflow_single,name='inflow_single'),
    path('inflow_files/', pick_views.inflow_files,name='inflow_files'),
    path('stock_single/', pick_views.stock_single,name='stock_single'),
    path('stock_select/', select_views.stock_select,name='stock_select'),
    path('index_single/', pick_views.index_single,name='index_single'),
    path('index_single1/', pick_views.index_single1,name='index_single1'),
    path('block_single/', pick_views.block_single,name='block_single'),
    path('stock_pe/', pick_views.stock_pe,name='stock_pe'),
    path('block_pe/', pick_views.block_pe,name='block_pe'),
    path('stock_nf/', pick_views.nf,name='stock_nf'),
    path('indexpe/', pick_views.indexpe,name='indexpe'),
    path('indexinflow/', pick_views.indexinflow,name='indexinflow'),
    path('indexpe_single/', pick_views.indexpe_single,name='indexpe_single'),
    path('update_aslist/', pick_views.update_aslist,name='update_aslist'),
    path('same_aslist/', pick_views.same_aslist,name='same_aslist'),
    path('man/', pick_views.man,name='man'),
    path('rwxls/', pick_views.rwxls,name='rwxls'),
]

teststock/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from astocks import views as astocks_views


urlpatterns = [
    re_path(r'^$', accounts_views.home, name='home'),
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^login/$', accounts_views.login, name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),
    re_path(r'^api/(?P<code>\d+)$', astocks_views.single),
    re_path(r'^api/stockSql/$',astocks_views.stockList),
    re_path(r'^api/search/$',astocks_views.search),
    re_path(r'^api/query/$',astocks_views.query),
    re_path(r'^api/oldquery/$',astocks_views.oldquery),
    re_path(r'^person/$', accounts_views.new_person,name='new_person'),
    re_path(r'^newpick/$', accounts_views.new_pick,name='new_pick'),
    re_path(r'^newlimitup/$', accounts_views.new_limitup,name='new_limitup'),
    re_path(r'^handledd/$', astocks_views.handledd,name='handledd'),
    re_path(r'^handleto/$', astocks_views.handleto,name='handleto'),
    path('admin/', admin.site.urls),
    path('astocks/', include(('astocks.urls','astocks'),namespace='astocks')),
    path('boards/', include(('boards.urls','boards'),namespace='boards')),
    path('prediction/', include(('prediction.urls','prediction'),namespace='prediction')),
    path('pick/', include(('pick.urls','pick'),namespace='pick')),
]

templates/pickstock/limitup_confirm_delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}删除确认 - {{ block.super }}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'astocks:limitup' %}">选股</a></li>
  <li class="breadcrumb-item active">删除确认</li>
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p> 您确定! 您要删除 " {{ obj.name }} " ?</p>
    <input type="hidden" name='id' value="{{ obj.id }}">
    <button type="submit" class="btn btn-success">确认</button>
    {% if 'by' in request.session.keys %}
       <a href="/astocks/limitup_date?by={{ obj.pick_date|date:'Y-m-d'}}" class="btn btn-outline-secondary" role="button">取消</a>
 
    {% elif 'bytype' in request.session.keys  %}
      <a href="/astocks/limitup_type?bytype={{ request.session.bytype }}" class="btn btn-outline-secondary" role="button">取消</a>
    {% elif 'byboard' in request.session.keys  %}
      <a href="/astocks/limitup_board?byboard={{ request.session.byboard }}" class="btn btn-outline-secondary" role="button">取消</a>
    {% else %}
      <a href="{% url 'astocks:limitup' %}" class="btn btn-outline-secondary" role="button">取消</a>
    {% endif %}
</form>
{% endblock %}

templates/pickstock/limitup_list_by_board.html
{% extends 'base.html' %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'astocks:limitup' %}">涨停</a></li>
  <li class="breadcrumb-item active">涨停板块 {{ limitupboard.name }}</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>涨停日期</th>
        <th>股票名称</th>
        <th>涨停类型</th>
        <th>涨停理由</th>
        <th>题材</th>
        <th>警惕缺点</th>
        <th>次日表现</th>
        <th>10日涨停数量</th>
        <th>涨跌幅</th>
        <th>总结</th>
        <th>录入人</th>
        {% if user.is_authenticated and user.is_superuser %}
           <th colspan="2">操作</th>
        {% endif %} 
      </tr>
    </thead>
    <tbody>
      {% for choose in limitups %}
        {% url 'boards:stock_detail' choose.name choose.name as stock_url %}
        <tr>
          <td>
            <a href="/astocks/limitup_date?by={{ choose.pick_date|date:'Y-m-d' }}">{{ choose.pick_date|date:'Y-m-d' }}</a> 
          </td>
          <td class="align-middle">
            {{ choose.code }}
            <small class="text-muted d-block"><a href="{{ stock_url }}">{{ choose.name }}</a></small>
          </td>
          <td class="align-middle">
            {% with types=choose.types %}
              {% if types %}
                <small>
                  {% for type in types.all %}
                     <a href="/astocks/limitup_type?bytype={{ type.id }}">{{ type.name }}</a> ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.reasons }}
          </td>
          
          <td class="align-middle">
            {% with boards=choose.boards %}
              {% if boards %}
                <small>
                  {% for board in boards.all %}
                     {{ board.name }} ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.short }}
          </td>
          <td class="align-middle">
            {{ choose.ndperformance }}
          </td>
          <td class="align-middle">
            {% if choose.tenday_limits %}
              {{ choose.tenday_limits }}
            {% else %}  
                  <em></em>
            {% endif %}
          </td>
          <td class="align-middle">
            {% if choose.growth > 0 %}
               <span style="color:red">{{ choose.growth }}</span>
            {% else %}
               <span style="color:green">{{ choose.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <small>
            {{ choose.summary }}
            </small>
          </td>
          <td class="align-middle">
            {{ choose.person }}
          </td>
          {% if user.is_authenticated and user.is_superuser %}
            <td class="align-middle" >
              <a href="{% url 'astocks:edit_limitup_by_board' choose.pk limitupboard.pk %}" class="btn btn-outline-primary" role="button">编辑</a>
            </td>
            <td class="align-middle" >
              <a href="{% url 'astocks:delete_limitup_by_board' choose.pk limitupboard.pk %}" class="btn btn-outline-danger" role="button">删除</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/pickstock/limitup_list_by_date.html
{% extends 'base.html' %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'astocks:limitup' %}">涨停</a></li>
  <li class="breadcrumb-item active">涨停日期 {{ by }}</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>涨停日期</th>
        <th>股票名称</th>
        <th>涨停类型</th>
        <th>涨停理由</th>
        <th>题材</th>
        <th>警惕缺点</th>
        <th>次日表现</th>
        <th>10日涨停数量</th>
        <th>涨跌幅</th>
        <th>总结</th>
        <th>录入人</th>
        {% if user.is_authenticated and user.is_superuser %}
           <th colspan="2">操作</th>
        {% endif %} 
      </tr>
    </thead>
    <tbody>
      {% for choose in limitups %}
        {% url 'boards:stock_detail' choose.name choose.name as stock_url %}
        <tr>
          <td>
            {{ choose.pick_date | date:'Y-m-d'  }}
          </td>
          <td class="align-middle">
            {{ choose.code }}
            <small class="text-muted d-block"><a href="{{ stock_url }}">{{ choose.name }}</small>
          </td>
          <td class="align-middle">
            {% with types=choose.types %}
              {% if types %}
                <small>
                  {% for type in types.all %}
                  <a href="/astocks/limitup_type?bytype={{ type.id }}">{{ type.name }}</a> ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.reasons }}
          </td>
          
          <td class="align-middle">
            {% with boards=choose.boards %}
              {% if boards %}
                <small>
                  {% for board in boards.all %}
                    <a href="/astocks/limitup_board?byboard={{ board.id }}">{{ board.name }}</a> ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.short }}
          </td>
          <td class="align-middle">
            {{ choose.ndperformance }}
          </td>
          <td class="align-middle">
            {% if choose.tenday_limits %}
              {{ choose.tenday_limits }}
            {% else %}  
                  <em></em>
            {% endif %}
          </td>
          <td class="align-middle">
            {% if choose.growth > 0 %}
               <span style="color:red">{{ choose.growth }}</span>
            {% else %}
               <span style="color:green">{{ choose.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <small>
            {{ choose.summary }}
            </small>
          </td>
          <td class="align-middle">
            {{ choose.person }}
          </td>
          {% if user.is_authenticated and user.is_superuser %}
            <td class="align-middle" >
              <a href="{% url 'astocks:edit_limitup_by_date' choose.pk 'date' %}" class="btn btn-outline-primary" role="button">编辑</a>
            </td>
            <td class="align-middle" >
              <a href="{% url 'astocks:delete_limitup_by_date' choose.pk 'date' %}" class="btn btn-outline-danger" role="button">删除</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/pickstock/limitup_list_by_type.html
{% extends 'base.html' %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'astocks:limitup' %}">涨停</a></li>
  <li class="breadcrumb-item active">涨停类型 {{ limituptype.name }}</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>涨停日期</th>
        <th>股票名称</th>
        <th>涨停类型</th>
        <th>涨停理由</th>
        <th>题材</th>
        <th>警惕缺点</th>
        <th>次日表现</th>
        <th>10日涨停数量</th>
        <th>涨跌幅</th>
        <th>总结</th>
        <th>录入人</th>
        {% if user.is_authenticated and user.is_superuser %}
           <th colspan="2">操作</th>
        {% endif %} 
      </tr>
    </thead>
    <tbody>
      {% for choose in limitups %}
        {% url 'boards:stock_detail' choose.name choose.name as stock_url %}
        <tr>
          <td>
            <a href="/astocks/limitup_date?by={{ choose.pick_date|date:'Y-m-d' }}">{{ choose.pick_date|date:'Y-m-d' }}</a> 
          </td>
          <td class="align-middle">
            {{ choose.code }}
            <small class="text-muted d-block"><a href="{{ stock_url }}">{{ choose.name }}</a></small>
          </td>
          <td class="align-middle">
            {% with types=choose.types %}
              {% if types %}
                <small>
                  {% for type in types.all %}
                      {{ type.name }} ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.reasons }}
          </td>
          
          <td class="align-middle">
            {% with boards=choose.boards %}
              {% if boards %}
                <small>
                  {% for board in boards.all %}
                    <a href="/astocks/limitup_board?byboard={{ board.id }}">{{ board.name }}</a> ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.short }}
          </td>
          <td class="align-middle">
            {{ choose.ndperformance }}
          </td>
          <td class="align-middle">
            {% if choose.tenday_limits %}
              {{ choose.tenday_limits }}
            {% else %}  
                  <em></em>
            {% endif %}
          </td>
          <td class="align-middle">
            {% if choose.growth > 0 %}
               <span style="color:red">{{ choose.growth }}</span>
            {% else %}
               <span style="color:green">{{ choose.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <small>
            {{ choose.summary }}
            </small>
          </td>
          <td class="align-middle">
            {{ choose.person }}
          </td>
          {% if user.is_authenticated and user.is_superuser %}
            <td class="align-middle" >
              <a href="{% url 'astocks:edit_limitup_by_type' choose.pk limituptype.pk %}" class="btn btn-outline-primary" role="button">编辑</a>
            </td>
            <td class="align-middle" >
              <a href="{% url 'astocks:delete_limitup_by_type' choose.pk limituptype.pk %}" class="btn btn-outline-danger" role="button">删除</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/pickstock/pickstock_list_by_board.html
{% extends 'base.html' %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'astocks:home' %}">选股</a></li>
  <li class="breadcrumb-item active">选股板块 {{ chooseboard.name }}</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>选股日期</th>
        <th>股票名称</th>
        <th>选股类型</th>
        <th>选股理由</th>
        <th>热点题材</th>
        <th>警惕缺点</th>
        <th>次日表现</th>
        <th>10日涨停数量</th>
        <th>涨跌幅</th>
        <th>经验总结</th>
        <th>选股人</th>
        {% if user.is_authenticated and user.is_superuser %}
           <th colspan="2">操作</th>
        {% endif %} 
      </tr>
    </thead>
    <tbody>
      {% for choose in chooses %}
        {% url 'boards:stock_detail' choose.name choose.name as stock_url %}
        <tr>
          <td>
            <a href="/astocks/choose_date?by={{ choose.pick_date|date:'Y-m-d' }}">{{ choose.pick_date|date:'Y-m-d' }}</a> 
          </td>
          <td class="align-middle">
            {{ choose.code }}
            <small class="text-muted d-block"><a href="{{ stock_url }}">{{ choose.name }}</a></small>
          </td>
          <td class="align-middle">
            {% with types=choose.types %}
              {% if types %}
                <small>
                  {% for type in types.all %}
                  <a href="/astocks/choose_type?bytype={{ type.id }}">{{ type.name }}</a> ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  

          <td class="align-middle">
            {{ choose.reasons }}
          </td>
          
          <td class="align-middle">
            {% with boards=choose.boards %}
              {% if boards %}
                <small>
                  {% for board in boards.all %}
                    {{ board.name }},
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.short }}
          </td>
          <td class="align-middle">
            {{ choose.ndperformance }}
          </td>
          <td class="align-middle">
            {% if choose.tenday_limits %}
              {{ choose.tenday_limits }}
            {% else %}  
                  <em></em>
            {% endif %}
          </td>
          <td class="align-middle">
            {% if choose.growth > 0 %}
               <span style="color:red">{{ choose.growth }}</span>
            {% else %}
               <span style="color:green">{{ choose.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <small>
            {{ choose.summary }}
            </small>
          </td>
          <td class="align-middle">
            {{ choose.person }}
          </td>
          {% if user.is_authenticated and user.is_superuser %}
            <td class="align-middle" >
              <a href="{% url 'astocks:edit_pick_by_board' choose.pk chooseboard.pk %}" class="btn btn-outline-primary" role="button">编辑</a>
            </td>
            <td class="align-middle" >
              <a href="{% url 'astocks:delete_pick_by_board' choose.pk chooseboard.pk %}" class="btn btn-outline-danger" role="button">删除</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/pickstock/pickstock_list_by_date.html
{% extends 'base.html' %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'astocks:home' %}">选股</a></li>
  <li class="breadcrumb-item active">选股日期 {{ by }}</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>选股日期</th>
        <th>股票名称</th>
        <th>选股类型</th>
        <th>选股理由</th>
        <th>热点题材</th>
        <th>警惕缺点</th>
        <th>次日表现</th>
        <th>10日涨停数量</th>
        <th>涨跌幅</th>
        <th>经验总结</th>
        <th>选股人</th>
        {% if user.is_authenticated and user.is_superuser %}
           <th colspan="2">操作</th>
        {% endif %} 
      </tr>
    </thead>
    <tbody>
      {% for choose in chooses %}
        {% url 'boards:stock_detail' choose.name choose.name as stock_url %}
        <tr>
          <td>
            {{ choose.pick_date | date:'Y-m-d'  }}
          </td>
          <td class="align-middle">
            {{ choose.code }}
            <small class="text-muted d-block"><a href="{{ stock_url }}">{{ choose.name }}</a></small>
          </td>
          <td class="align-middle">
            {% with types=choose.types %}
              {% if types %}
                <small>
                  {% for type in types.all %}
                  <a href="/astocks/limitup_type?bytype={{ type.pk }}">{{ type.name }}</a> ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  

          <td class="align-middle">
            {{ choose.reasons }}
          </td>
          
          <td class="align-middle">
            {% with boards=choose.boards %}
              {% if boards %}
                <small>
                  {% for board in boards.all %}
                  <a href="/astocks/choose_board?byboard={{ board.id }}">{{ board.name }}</a> ,
                  {% endfor %}
                </small>
              {% else %}
                <small class="text-muted">
                  <em></em>
                </small>
              {% endif %}
            {% endwith %}
          </td>  
          <td class="align-middle">
            {{ choose.short }}
          </td>
          <td class="align-middle">
            {{ choose.ndperformance }}
          </td>
          <td class="align-middle">
            {% if choose.tenday_limits %}
              {{ choose.tenday_limits }}
            {% else %}  
                  <em></em>
            {% endif %}
          </td>
          <td class="align-middle">
            {% if choose.growth > 0 %}
               <span style="color:red">{{ choose.growth }}</span>
            {% else %}
               <span style="color:green">{{ choose.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <small>
            {{ choose.summary }}
            </small>
          </td>
          <td class="align-middle">
            {{ choose.person }}
          </td>
          {% if user.is_authenticated and user.is_superuser %}
            <td class="align-middle" >
              <a href="{% url 'astocks:edit_pick_by_date' choose.pk 'date' %}" class="btn btn-outline-primary" role="button">编辑</a>
            </td>
            <td class="align-middle" >
              <a href="{% url 'astocks:delete_pick_by_date' choose.pk 'date' %}" class="btn btn-outline-danger" role="button">删除</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}