astocks/urls.py
from django.urls import re_path
from .view import pick_views,limitup_views

urlpatterns = [ 
    re_path(r'^$', pick_views.StockChooseListView.as_view(), name='home'),
    re_path(r'^edit_pick/(?P<id>\d+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick'), 
    re_path(r'^delete_pick/(?P<id>\d+)/$', pick_views.DeleteStockChooseView.as_view(), name='delete_pick'), 
    re_path(r'^edit_pick/(?P<id>\d+)/(?P<by>[a-z]+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick_by_date'), 
    re_path(r'^delete_pick/(?P<id>\d+)/(?P<by>[a-z]+)/$', pick_views.DeleteStockChooseByDateView.as_view(), name='delete_pick_by_date'), 
    re_path(r'^edit_pick/(?P<id>\d+)/(?P<bytype>\d+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick_by_type'), 
    re_path(r'^delete_pick/(?P<id>\d+)/(?P<bytype>\d+)/$', pick_views.DeleteStockChooseByTypeView.as_view(), name='delete_pick_by_type'), 
    re_path(r'^edit_pick/(?P<id>\d+)/(?P<byboard>\d+)/$', pick_views.EditStockChooseView.as_view(), name='edit_pick_by_board'), 
    re_path(r'^delete_pick/(?P<id>\d+)/(?P<byboard>\d+)/$', pick_views.DeleteStockChooseByBoardView.as_view(), name='delete_pick_by_board'), 
    re_path(r'^choose_date/$', pick_views.byDateListView,name='choose_date'),  
    re_path(r'^choose_type/$', pick_views.byTypeListView,name='choose_type'), 
    re_path(r'^choose_board/$', pick_views.byBoardListView,name='choose_board'),   
    re_path(r'^choose_detail/(?P<name>.+)/$', pick_views.choose_detail,name='choose_detail'), 
    re_path(r'^limitup/$', limitup_views.StockChooseListView.as_view(), name='limitup'),
    re_path(r'^edit_limitup/(?P<id>\d+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/$', limitup_views.DeleteStockChooseView.as_view(), name='delete_limitup'), 
    re_path(r'^edit_limitup/(?P<id>\d+)/(?P<by>[a-z]+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup_by_date'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/(?P<by>[a-z]+)/$', limitup_views.DeleteStockChooseByDateView.as_view(), name='delete_limitup_by_date'), 
    re_path(r'^edit_limitup/(?P<id>\d+)/(?P<bytype>\d+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup_by_type'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/(?P<bytype>\d+)/$', limitup_views.DeleteStockChooseByTypeView.as_view(), name='delete_limitup_by_type'), 
    re_path(r'^edit_limitup/(?P<id>\d+)/(?P<byboard>\d+)/$', limitup_views.EditStockChooseView.as_view(), name='edit_limitup_by_board'), 
    re_path(r'^delete_limitup/(?P<id>\d+)/(?P<byboard>\d+)/$', limitup_views.DeleteStockChooseByBoardView.as_view(), name='delete_limitup_by_board'), 
    re_path(r'^limitup_date/$', limitup_views.byDateListView,name='limitup_date'),
    re_path(r'^limitup_type/$', limitup_views.byTypeListView,name='limitup_type'),
    re_path(r'^limitup_board/$', limitup_views.byBoardListView,name='limitup_board'),
    re_path(r'^limitup_detail/(?P<name>.+)/$', limitup_views.limitup_detail,name='limitup_detail'), 
]

boards/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [ 
    re_path(r'^$', views.BoardListView.as_view(), name='home'),
    re_path(r'^(?P<pk>\d+)/types/(?P<type_pk>\d+)/$', views.ByTypeBoardListView.as_view(), name='type_boards'),
    re_path(r'^(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    re_path(r'^(?P<name>.+)/stocks/$', views.StockListView.as_view(), name='board_stocks'),
    re_path(r'^(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    re_path(r'^(?P<board_name>.+)/stocks/(?P<stock_name>.+)/$', views.stock_detail, name='stock_detail'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/edit/$',
        views.TopicUpdateView.as_view(), name='edit_topic'),
    re_path(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),
    path('query', views.query, name='query'),
    path('blockquery', views.blockquery, name='blockquery'),
    path('blockget', views.blockget, name='blockget'),
    path('singleget', views.singleget, name='singleget'),
    path('dtype_boards', views.ByDTypeBoardListView.as_view(), name='dtype_boards'),
]

pick/urls.py
from django.urls import re_path,path
from . import views as pick_views
from .view import pick_views as select_views

urlpatterns = [ 
    re_path(r'^$', pick_views.home, name='home'),
    path('query/', pick_views.query,name='query'),  
    path('jquery/', pick_views.jquery,name='jquery'), 
    path('pe_dayadd/', pick_views.pe_dayadd,name='pe_dayadd'), 
    path('dayadd/', pick_views.dayadd,name='dayadd'), 
    path('blockadd/', pick_views.blockadd,name='blockadd'), 
    path('indexadd/', pick_views.indexadd,name='indexadd'), 
    path('blockdayadd/', pick_views.blockdayadd,name='blockdayadd'), 
    path('dayout/', pick_views.dayout,name='dayout'), 
    path('inflow/', pick_views.inflow,name='inflow'),
    path('binflow/', pick_views.binflow,name='binflow'),
    path('inflow_single/', pick_views.inflow_single,name='inflow_single'),
    path('inflow_files/', pick_views.inflow_files,name='inflow_files'),
    path('stock_single/', pick_views.stock_single,name='stock_single'),
    path('stock_select/', select_views.stock_select,name='stock_select'),
    path('index_single/', pick_views.index_single,name='index_single'),
    path('index_single1/', pick_views.index_single1,name='index_single1'),
    path('block_single/', pick_views.block_single,name='block_single'),
    path('stock_pe/', pick_views.stock_pe,name='stock_pe'),
    path('block_pe/', pick_views.block_pe,name='block_pe'),
    path('stock_nf/', pick_views.nf,name='stock_nf'),
    path('indexpe/', pick_views.indexpe,name='indexpe'),
    path('indexinflow/', pick_views.indexinflow,name='indexinflow'),
    path('indexpe_single/', pick_views.indexpe_single,name='indexpe_single'),
    path('update_aslist/', pick_views.update_aslist,name='update_aslist'),
    path('same_aslist/', pick_views.same_aslist,name='same_aslist'),
    path('man/', pick_views.man,name='man'),
    path('rwxls/', pick_views.rwxls,name='rwxls'),
]

teststock/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from astocks import views as astocks_views


urlpatterns = [
    re_path(r'^$', accounts_views.home, name='home'),
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^login/$', accounts_views.login, name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),
    re_path(r'^api/(?P<code>\d+)$', astocks_views.single),
    re_path(r'^api/stockSql/$',astocks_views.stockList),
    re_path(r'^api/search/$',astocks_views.search),
    re_path(r'^api/query/$',astocks_views.query),
    re_path(r'^api/oldquery/$',astocks_views.oldquery),
    re_path(r'^person/$', accounts_views.new_person,name='new_person'),
    re_path(r'^newpick/$', accounts_views.new_pick,name='new_pick'),
    re_path(r'^newlimitup/$', accounts_views.new_limitup,name='new_limitup'),
    re_path(r'^handledd/$', astocks_views.handledd,name='handledd'),
    re_path(r'^handleto/$', astocks_views.handleto,name='handleto'),
    path('admin/', admin.site.urls),
    path('astocks/', include(('astocks.urls','astocks'),namespace='astocks')),
    path('boards/', include(('boards.urls','boards'),namespace='boards')),
    path('prediction/', include(('prediction.urls','prediction'),namespace='prediction')),
    path('pick/', include(('pick.urls','pick'),namespace='pick')),
]

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}爱校码股票{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %} 
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    {% block hjavascript %}{% endblock %}
  </head>
  <body>
    {% block body %}
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'boards:home' %}">
            <img src="{% static 'img/logo.png' %}" alt="爱校码股票" style="width:40px;">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'boards:home' %}">股票论坛</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://stock.ischoolcode.cn:9000">股票分析</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'prediction:home' %}">智能预测</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'astocks:home' %}">选股信息</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'astocks:limitup' %}">涨停观察</a>
              </li>
            </ul>
            {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    {% if user.is_superuser %}
                      <a class="dropdown-item" href="{% url 'handledd' %}">股票日线基本数据</a>
                      <a class="dropdown-item" href="{% url 'handleto' %}">股票日线换手率</a>
                      <a class="dropdown-item" href="{% url 'new_person' %}">新建选股人</a>
                      <a class="dropdown-item" href="{% url 'new_pick' %}">新建选股</a>
                      <a class="dropdown-item" href="{% url 'new_limitup' %}">新建涨停</a>
                    {% else %}
                       <a class="dropdown-item" href="#">我的帐户</a>
                       <a class="dropdown-item" href="#">更改密码</a>
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">注销</a>
                  </div>
                </li>
              </ul>
            {% else %}
              <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">登录</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">注册</a>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
      <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'boards:home' %}">爱校码股票</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}

{% load static %}

{% block title %}编辑帖子{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">编辑帖子</li>
{% endblock %}

{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">更新</button>
    <a href="{% url 'boards:topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">取消</a>
  </form>
{% endblock %}

templates/edit_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}编辑主题{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
  {% comment %} <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li> {% endcomment %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">编辑主题</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">更新</button>
    <a href="{% url 'boards:board_topics' topic.board.pk %}" class="btn btn-outline-secondary" role="button">取消</a>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block breadcrumb %}
  <li class="breadcrumb-item active">板块</li>
  <li class="ml-auto">
    <span>
        <form align="left"  id="myblock">
            {% csrf_token %}
            <input id="block" name="block" type="text" placeholder="板块名称" 
              autofocus required size="12"> 
            <button type="submit" class="btn btn-success" >查询</button>
        </form>
    </span>
  </li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>板块</th>
        <th>涨跌幅%</th>
        <th>类别</th>
        <th>帖子</th>
        <th>主题</th>
        <th>最后发表</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">
            {% if board.growth > 0 and board.type.name != '普通' %}
               <span style="color:red">{{ board.growth }}</span>
            {% elif board.type.name != '普通' %}
               <span style="color:green">{{ board.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            {% if board.type.name == '普通' %}
               {{ board.type.name }}
            {% else %}
               <a href="{% url 'boards:type_boards' board.pk  board.type.pk %}">{{ board.type.name }}</a>
            {% endif %}
          </td>
          <td class="align-middle">
            {{ board.get_posts_count }}
          </td>
          <td class="align-middle">
            {{ board.topics.count }}
          </td>
          <td class="align-middle">
            {% with post=board.get_last_post %}
              {% if post %}
                <small>
                  <a href="{% url 'boards:topic_posts' board.pk post.topic.pk %}">
                    由 {{ post.created_by.username }} 在 {{ post.created_at }}发表
                  </a>
                </small>
              {% else %}
                <small class="text-muted">
                  <em>还没有帖子。</em>
                </small>
              {% endif %}
            {% endwith %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'includes/pagination.html' %}
  <div class="modal fade" id="notfindModel">
    <div class="modal-dialog">
        <div class="modal-content message_align" style="width:400px;height:80px;margin-top:220px;margin-left:130px">
            <div class="modal-header" style="text-align:left;font-size:small;height:3px;margin-bottom:1px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top:-30px"><span
                        aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body" style="text-align: center;font-size:16px;height: 18px;color:chocolate">
                <p style="margin-top:-15px">没有找到查询的板块</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <div class="modal fade" id="preModel">
    <div class="modal-dialog">
        <div class="modal-content" style="width:400px;height:80px;margin-top:220px;margin-left:130px">
            <div class="modal-header" style="text-align:left;font-size:small;height:3px;margin-bottom:1px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top:-30px"><span
                    aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body" style="text-align: center;font-size:16px;height: 18px;color:chocolate">
                <p style="margin-top:-15px">正在查询中，请耐心等待......</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success">查询结束将关闭</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
{% endblock %}
{% block javascript %}
<script>

$(document).ready(function(){
  $.ajaxSetup({
      data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
  });

  $('#myblock').submit(function(){
      var blockname = $("#block").val();
      $.ajax({
              type:"POST",
              data: {blockname:blockname},
              url: "{% url 'boards:blockquery' %}",
              cache: false,
              dataType: "json",
              success: function (res) {
                  if (res.data){
                      var data = JSON.parse(res.data); 
                      if (data.result=="success"){
                          location = "/boards/"+blockname+"/stocks/";
                      }else{
                          $('#notfindModel').modal('show');
                          setTimeout(function(){
                             $('#notfindModel').modal('hide');  
                          }, 3000); //ms为单位
                      }
                  }
              },
              error: function (msg) {
                  alert(JSON.stringify(msg));
              }
      });
              
      return false;    
  });
});
</script> 
{% endblock %}

templates/homebytype.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item active">{{ type.name }}</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>板块</th>
        <th>涨跌幅（%）</th>
        <th>当天涨停</th>
        <th>30天涨停</th>
        <th>连涨天数</th>
        <th>上涨，下跌</th>
        <th>主力净流入（万）</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'boards:board_stocks' board.name %}">{{ board.name }}</a>
          </td>
          <td class="align-middle">
            {% if board.growth > 0 %}
               <span style="color:red">{{ board.growth }}</span>
            {% else %}
               <span style="color:green">{{ board.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <span style="color:red">{{ board.limitup_number }}</span>
          </td>
          <td class="align-middle">
            <span style="color:red">{{ board.Continuerise_30_limitup }}</span>
          </td>
          <td class="align-middle">
            {% if board.Continuerise_days > 0 %}
               <span style="color:red">{{ board.Continuerise_days }}</span>
            {% else %}
               <span style="color:green">{{ board.Continuerise_days }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <span style="color:blue">{{ board.growth_fall }}</span>
          </td>
          <td class="align-middle">
            {% if board.inflow > 0 %}
               <span style="color:red">{{ board.inflow }}</span>
            {% else %}
               <span style="color:green">{{ board.inflow }}</span>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'includes/pagination.html' %}
{% endblock %}

templates/homedbytype.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item active">大盘</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>板块</th>
        <th>涨跌幅（%）</th>
        <th>流入（万）</th>
        <th>流出（万）</th>
        <th>主力净流入（万）</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'boards:board_stocks' board.name %}">{{ board.name }}</a>
          </td>
          <td class="align-middle">
            {% if board.growth > 0 %}
               <span style="color:red">{{ board.growth }}</span>
            {% else %}
               <span style="color:green">{{ board.growth }}</span>
            {% endif %}
          </td>
          <td class="align-middle">
            <span style="color:red">{{ board.inf }}</span>
          </td>
          <td class="align-middle">
            <span style="color:green">{{ board.outf }}</span>
          </td>
          <td class="align-middle">
            {% if board.inflow > 0 %}
               <span style="color:red">{{ board.inflow }}</span>
            {% else %}
               <span style="color:green">{{ board.inflow }}</span>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'includes/pagination.html' %}
{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}登录 - {{ block.super }}{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">登录</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">登录</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
            爱校码股票的新用户? <a href="{% url 'signup' %}">注册</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
            <a href="#" class="text-muted">忘记密码了吗?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}开启一个新主题{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
  {% comment %} <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li> {% endcomment %}
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">新建主题</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">发布</button>
    <a href="{% url 'boards:board_topics' board.pk %}" class="btn btn-outline-secondary" role="button">取消</a>
  </form>
{% endblock %}

templates/topic_posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">板块</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}
  <div class="mb-4">
    <a href="{% url 'boards:reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">回帖</a>
  </div>
  
  {% for post in posts %}
    <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
        <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
      {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'img/avatar.svg' %}" alt="{{ post.created_by.username }}" class="w-100"/>
            <small>帖子: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at|date:"Y-m-d H:i:s"}}</small>
              </div>
            </div>
            {{ post.get_message_as_markdown }}
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'boards:edit_post' post.topic.board.pk post.topic.pk post.pk %}"
                     class="btn btn-primary btn-sm" role="button">编辑</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  {% include 'includes/pagination.html' %}
{% endblock %}