pick/urls.py
from django.urls import re_path,path
from . import views as pick_views
from .view import pick_views as select_views

urlpatterns = [ 
    re_path(r'^$', pick_views.home, name='home'),
    path('query/', pick_views.query,name='query'),  
    path('jquery/', pick_views.jquery,name='jquery'), 
    path('pe_dayadd/', pick_views.pe_dayadd,name='pe_dayadd'), 
    path('dayadd/', pick_views.dayadd,name='dayadd'), 
    path('blockadd/', pick_views.blockadd,name='blockadd'), 
    path('indexadd/', pick_views.indexadd,name='indexadd'), 
    path('blockdayadd/', pick_views.blockdayadd,name='blockdayadd'), 
    path('dayout/', pick_views.dayout,name='dayout'), 
    path('inflow/', pick_views.inflow,name='inflow'),
    path('binflow/', pick_views.binflow,name='binflow'),
    path('inflow_single/', pick_views.inflow_single,name='inflow_single'),
    path('inflow_files/', pick_views.inflow_files,name='inflow_files'),
    path('stock_single/', pick_views.stock_single,name='stock_single'),
    path('stock_select/', select_views.stock_select,name='stock_select'),
    path('index_single/', pick_views.index_single,name='index_single'),
    path('index_single1/', pick_views.index_single1,name='index_single1'),
    path('block_single/', pick_views.block_single,name='block_single'),
    path('stock_pe/', pick_views.stock_pe,name='stock_pe'),
    path('block_pe/', pick_views.block_pe,name='block_pe'),
    path('stock_nf/', pick_views.nf,name='stock_nf'),
    path('indexpe/', pick_views.indexpe,name='indexpe'),
    path('indexinflow/', pick_views.indexinflow,name='indexinflow'),
    path('indexpe_single/', pick_views.indexpe_single,name='indexpe_single'),
    path('update_aslist/', pick_views.update_aslist,name='update_aslist'),
    path('same_aslist/', pick_views.same_aslist,name='same_aslist'),
    path('man/', pick_views.man,name='man'),
    path('rwxls/', pick_views.rwxls,name='rwxls'),
]

prediction/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [ 
   re_path(r'^$', views.redirect_root,name='home'),        
   path('pred', views.pred, name='pred'),
   path('pypred', views.pypred, name='pypred'),
]

teststock/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from astocks import views as astocks_views


urlpatterns = [
    re_path(r'^$', accounts_views.home, name='home'),
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^login/$', accounts_views.login, name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),
    re_path(r'^api/(?P<code>\d+)$', astocks_views.single),
    re_path(r'^api/stockSql/$',astocks_views.stockList),
    re_path(r'^api/search/$',astocks_views.search),
    re_path(r'^api/query/$',astocks_views.query),
    re_path(r'^api/oldquery/$',astocks_views.oldquery),
    re_path(r'^person/$', accounts_views.new_person,name='new_person'),
    re_path(r'^newpick/$', accounts_views.new_pick,name='new_pick'),
    re_path(r'^newlimitup/$', accounts_views.new_limitup,name='new_limitup'),
    re_path(r'^handledd/$', astocks_views.handledd,name='handledd'),
    re_path(r'^handleto/$', astocks_views.handleto,name='handleto'),
    path('admin/', admin.site.urls),
    path('astocks/', include(('astocks.urls','astocks'),namespace='astocks')),
    path('boards/', include(('boards.urls','boards'),namespace='boards')),
    path('prediction/', include(('prediction.urls','prediction'),namespace='prediction')),
    path('pick/', include(('pick.urls','pick'),namespace='pick')),
]

prediction/models.py
from django.db import models

# Create your models here.
import json

class Company(models.Model):
    stock_code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)

class StockIndex(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    ri_qi = models.CharField(max_length=30)
    zi_jin = models.IntegerField(default=0)
    qiang_du = models.IntegerField(default=0)
    feng_xian = models.IntegerField(default=0)
    zhuan_qiang = models.IntegerField(default=0)
    chang_yu = models.IntegerField(default=0)
    jin_zi = models.IntegerField(default=0)
    zong_he = models.IntegerField(default=0)

class HistoryData(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    data = models.TextField() # 字符串类型
    start_date = models.CharField(max_length=30)

    def set_data(self,list_data):   # 将list类型数据，转为字符串存储
        try:
            start_da = list_data[0][0]  # 记录第一条数据的日期
            data_json = json.dumps(list_data)  # 可以将list或dict类型 转为字符串
        except (KeyError,TypeError,IndexError):
            raise Exception("list_data must be 2 dimensions list.")
        else:
            self.start_date = start_da
            self.data = data_json

    def get_data(self):
        return json.loads(self.data)        # 可以将字符串 转为list或dict类型

class PredictData(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    data = models.TextField()  # 字符串类型
    start_date = models.CharField(max_length=30)

    def set_data(self, list_data):  # 将list类型数据，转为字符串存储
        try:
            st_da = list_data[0][0]  # 记录第一条数据的日期
            data_json = json.dumps(list_data)  # 可以将list或dict类型 转为字符串
        except (KeyError,TypeError):
            raise Exception("list_data must be 2 dimensions list.")
        else:
            self.start_date = st_da
            self.data = data_json

    def get_data(self):
        return json.loads(self.data)  # 可以将字符串 转为list或dict类型

prediction/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

class CodeForm(forms.Form):
    code = forms.CharField(
        label=_('股票代码'),
        required=True,
        error_messages={'required':'这是必填栏。'},
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder': '填写股票代码...'}))
    
    class Meta:
        fields = ('code', )
        

prediction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, JsonResponse
from django.shortcuts import render, get_object_or_404
from astocks.models import StockList
from .models import Company
from . import models
from .LSTMPredictStock import predic,pypredic
from .add_companies_to_db import add_company
from .forms import CodeForm
import json
import os
from datetime import datetime as dt
# from apscheduler.scheduler import Scheduler
import pandas as pd
from django.http import Http404, HttpResponse

# --------------- MAIN WEB PAGES -----------------------------
def redirect_root(request):
    return redirect('/prediction/pred')

def pypred(request):
    predic.pytrain_model("605111")
    return HttpResponse('执行完毕！')
    
def pred(request):
    if request.method == 'POST':
        form = CodeForm(request.POST)
        if form.is_valid():
            opt  = request.POST['opt']
            if opt == '1':
                stock_code = request.POST['code']
                again = request.POST['again']
                good = request.POST['good']
                if good != 'on':
                    predic.train_model(stock_code)
                else:
                    if not predic.isGood(stock_code):
                        return JsonResponse({"data":False }) 
           
                recent_data, predict_data,code,name = get_hist_predict_data(stock_code,again,good)
                data = {"recent_data": recent_data, "predict_data": predict_data,"stock_code": code,"stock_name": name}
                # data['indexs'] = get_stock_index(code)
                return JsonResponse({"data": json.dumps(data)}) 
                # return render(request, "prediction/home.html", {"data": json.dumps(data),'form': form}) 
            else:
                stock_code = request.POST['code']
                stock = get_object_or_404(StockList, symbol=stock_code)
                again = request.POST['again']
                good = request.POST['good']
                info = pypredic.main(stock_code,good,again)
                
                data = {"info": info,"stock_code": stock_code,"stock_name": stock.name}
                return JsonResponse({"data": json.dumps(data)})  
    else:
        form = CodeForm()
     
    return render(request, 'prediction/prediction.html',{'form': form})


######################################################
#      
#
######################################################
def get_hist_predict_data(stock_code,again,good):
    try:
        company = get_object_or_404(Company, stock_code=stock_code)
    except Http404:
        stock = get_object_or_404(StockList, symbol=stock_code)
        company = Company()
        company.name = stock.name
        company.stock_code = stock_code
        company.save()

    recent_data,predict_data = None,None
    
    if company.historydata_set.count() <= 0:
        history_data = models.HistoryData()
        history_data.company = company
        history_data.set_data(predic.get_hist_data(stock_code, good, recent_day=22))
        history_data.save()
        recent_data = history_data.get_data()
    else:
        all_data = company.historydata_set.all()
        for single in all_data:
            now = dt.now()
            end_date = single.get_data()[-1][0]
            end_date = dt.strptime(end_date,"%Y-%m-%d")
           
            if  (now.date() > end_date.date() or good == 'on'):  # 更新历史数据
                single.set_data(predic.get_hist_data(stock_code, good, recent_day=22))
                single.save()

            recent_data = single.get_data()
            break

    if company.predictdata_set.count() <= 0:
        predict_data = models.PredictData()
        predict_data.company = company
        predict_data.set_data(predic.prediction(stock_code, good, pre_len=5))
        predict_data.save()
        predict_data = predict_data.get_data()
    else:
        all_data = company.predictdata_set.all()
        for single in all_data:
            now = dt.now()
            start_date = dt.strptime(single.start_date,"%Y-%m-%d")
            if (now.date() > start_date.date() or again == 'on' or good == 'on'):  # 更新预测数据
                single.set_data(predic.prediction(stock_code, good, pre_len=5))
                single.save()

            predict_data = single.get_data()
            break

    return recent_data,predict_data,stock_code,company.name


def get_crawl_save_data():
    """
    将10个公司的指标数据爬取并保存到数据库
    """
    # 此处应是从网上爬取数据，并保存为csv文件
    parent_dir = os.path.dirname(__file__)  # "stock_predict/views.py"
    file_dir = os.path.join(parent_dir, "stock_index/")
    for file_name in os.listdir(file_dir):
        file_path =  os.path.join(file_dir, file_name)
        data_frame = pd.read_csv(file_path)
        stock_code = file_name.split('.')[0]
        company = get_object_or_404(Company, stock_code=stock_code)
        for index,row in data_frame.iterrows():
            company.stockindex_set.create(ri_qi=row['ri_qi'],zi_jin=row['zi_jin'],qiang_du=row['qiang_du'],feng_xian=row['feng_xian'],
                zhuan_qiang=row['zhuan_qiang'],chang_yu=row['chang_yu'],jin_zi=row['jin_zi'],zong_he=row['zong_he'])


def get_stock_index(stock_code):
    """
    获取股票的各项指标数据
    """
    company = get_object_or_404(Company, stock_code=stock_code)
    if company.stockindex_set.count() <= 0:
        # 将爬取的数据存入数据库
        get_crawl_save_data()
    # 从数据库获取近三天的数据
    indexs = company.stockindex_set.all().order_by('-ri_qi')[:3].values()
    return list(indexs)

""" sched = Scheduler()
# 定时任务
# @sched.interval_schedule(seconds=2)   # 每2s执行一次
@sched.cron_schedule(hour=0,minute=0)   # 每日凌晨调度一次
def train_models():
    predic.train_all_stock()

sched.start() """
#########################################################################################
#
#
#########################################################################################

templates/prediction/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="background-image: url(http://stock.ischoolcode.cn/static/prediction/img/rmb.png);">
    <head>
        {% load static %}
        <link rel="icon" href="{% static 'img/favicon.ico' %}"/>
        <title>
            爱校码股票预测
        </title>
        <link rel="stylesheet" href="{% static 'prediction/css/bootstrap.min.css'%}" type="text/css">
        <!-- get the required files from 3rd party sources -->
        <link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
            <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
            <link href="{% static 'prediction/css/style.css' %}" rel="stylesheet" type="text/css"/>
            <!-- Bootstrap -->
            <link href="{% static 'prediction/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
                <link href="{% static 'prediction/fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css">
                    <link href="{% static 'prediction/css/menusearch.css' %}" rel="stylesheet" type="text/css">
                        <!-- Stylesheet================================================== -->
                        <link href="{% static 'prediction/css/style.css' %}" rel="stylesheet" type="text/css"> 
                                <script src="{% static 'prediction/js/modernizr.custom.js' %}" type="text/javascript">
                                </script>
                                <link href="http://fonts.googleapis.com/css?family=Raleway:500,600,700,100,800,900,400,200,300" rel="stylesheet" type="text/css">
                                    <link href="http://fonts.googleapis.com/css?family=Playball" rel="stylesheet" type="text/css">
                                        <script src="{% static 'prediction/js/jquery.1.11.1.js' %}" type="text/javascript">
                                        </script>
                                    </link>
                                </link>
                            
                        </link>
                    </link>
                </link>
            </link>
        </link>
        {% block stylesheet %}{% endblock %} 

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'prediction/js/jquery.1.11.1.js'%}" type="text/javascript">
        </script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'prediction/js/bootstrap.min.js'%}" type="text/javascript">
        </script>
        <script type="text/javascript">
            function mouseOver() {
               document.getElementById("stocks_logo").style.color = "#fe001a";
               document.getElementById("preds_logo").style.color = "#97c950";
            }
            function mouseOut() {
               document.getElementById("stocks_logo").style.color = "#97c950";
               document.getElementById("preds_logo").style.color = "#fe001a";
            }
        </script>
        <!-- Javascripts -->
        {% block javascript %}{% endblock %}
    </head>
    <body>
        <div class="header" style="background-color: rgb(40, 40, 40); color: white;">
            <div class="logo">
                <h1>
                    <a href="index" onmouseover="mouseOver()" onmouseout="mouseOut()">
                        <span id="stocks_logo" style="margin-left:10px">
                           爱校码
                        </span>
                        <span id="preds_logo">
                           预测
                        </span>
                        <span id="stocks_logo">
                           股票
                        </span>
                        <br>
                            <small>
                                智能预测一站式解决方案！
                            </small>
                        </br>
                    </a>
                </h1>
            </div>
            <div class="menu_nav">
                <ul>
                    {% block nav %}{% endblock %}
                </ul>
            </div>
            <div class="clr">
            </div>
            <div class="hbg">
                <img alt="" class="fl" height="400px" src="{% static 'prediction/img/header_b.jpg' %}" width="100%"/>
            </div>
            <div class="clr">
            </div>
        </div>
        {% block content %}{% endblock %}
        <div class="clr">
        </div>
        <div class="fbg">
            <div class="fbg_resize">
                <div class="col c1">
                    <h2>
                        <span>
                            图片库
                        </span>
                    </h2>
                    <a href="#">
                        <img alt="" height="58" src="{% static 'prediction/img/image2.jpg' %}" width="58"/>
                    </a>
                    <a href="#">
                        <img alt="" height="58" src="{% static 'prediction/img/image3.jpg' %}" width="58"/>
                    </a>
                    <a href="#">
                        <img alt="" height="58" src="{% static 'prediction/img/image4.jpg' %}" width="58"/>
                    </a>
                    <a href="#">
                        <img alt="" height="58" src="{% static 'prediction/img/image5.jpg' %}" width="58"/>
                    </a>
                    <a href="#">
                        <img alt="" height="58" src="{% static 'prediction/img/image6.jpg' %}" width="58"/>
                    </a>
                    <a href="#">
                        <img alt="" height="58" src="{% static 'prediction/img/image7.jpg' %}" width="58"/>
                    </a>
                </div>
                <div class="col c3" style="width:620px">
                    <h2>
                        <span>
                            关于我们
                        </span>
                    </h2>
                    对于普通投资者来说，股市可能是一个令人困惑的地方。 我们寻求通过提供给您优势的信息来帮助普通个人投资者进行明智的投资。
                    《爱校码股票预测》 使用最先进的人工智能深度机器学习来预测股票价格并生成股票交易短期22天的历史趋势和未来5天的走势的预测信号，帮助您做出决定。
                </div>
            </div>
        </div>
        <div class="clr">
        </div>
        <div class="footer">
            <div class="footer_resize">
                <p class="lf" style="margin:10px">
                   &copy; 2020 - <script>document.write(new Date().getFullYear())</script> ischoolcode.cn 爱校码.中国 版权所有 <a href="http://beian.miit.gov.cn">粤ICP备19044405号</a>     
                </p>
                <div class="clr">
                </div>
            </div>
        </div>
        {% block javascript1 %}{% endblock %}
    </body>
</html>

templates/prediction/prediction.html
{% extends "prediction/base.html" %}
{% load static %}
{% block javascript %}
    <script type="text/javascript" src="{% static 'prediction/js/echarts.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'prediction/js/draw_charts.js' %}"></script>
    <script type="text/javascript">
        var stock_data = null;
        var recent_data = null;
        var stock_code = null;
        var predict_data = null;
        var stock_name = null;
        var indexs = null;

        var pydata=null;
        var info=null;
        var label_X=null;
        var predict_X=null;
        var label_data=null;
        var predict_data=null;
        $(document).ready(function(){
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
            });

            $('#myform').submit(function(){
                var code = $("#id_code").val();
                const radioButtons = document.getElementsByName('option');
                let value;
                for (let i = 0; i < radioButtons.length; i++) {
                    if (radioButtons[i].checked) {
                        value = radioButtons[i].value;
                        break;
                    }
                }
                
                var again = 'off';
                var good = 'off';
                
                if ($('input[name="again"]:checked').val()){
                    again = 'on';
                }
                if ($('input[name="good"]:checked').val()){
                    good = 'on';
                }

                if( again == 'on' && good == 'on' ){
                    $('#bothModel').modal({backdrop: 'static', keyboard: false});
                    $('#bothModel').modal('show');
                }else{
                    $.ajax({
                        type:"POST",
                        data: {code:code,again:again,good:good,opt:value},
                        url: "{% url 'prediction:pred' %}",
                        cache: false,
                        dataType: "json",
                        beforeSend: function(){
                            if( good == 'on' ){
                                $('#preModel').modal({backdrop: 'static', keyboard: false}); //设置模态框之外点击无效
                                $('#preModel').modal('show');      // 弹出模态框
                            }else{
                                $('#trainModel').modal({backdrop: 'static', keyboard: false}); //设置模态框之外点击无效
                                $('#trainModel').modal('show');      // 弹出模态框
                            }
                        },
                        success: function (res) {
                            if (value=='2'){
                                $('#preModel').modal('hide');  
                                $('#trainModel').modal('hide'); 
                                if (res.data){
                                    pydata = JSON.parse(res.data);
                                    info = pydata.info;
                                    stock_code = pydata.stock_code;
                                    stock_name = pydata.stock_name;
                                }  
                                
                                if(info != null){
                                    draw_lowhigh();
                                }
                            }else{
                                if( good == 'on' ){
                                    $('#preModel').modal('hide');  
                                    if (res.data){
                                        stock_data = JSON.parse(res.data); 
                                        recent_data = stock_data.recent_data;
                                        predict_data = stock_data.predict_data;
                                        stock_code = stock_data.stock_code;
                                        stock_name = stock_data.stock_name;
                                    }else{
                                        $('#nogoodModel').modal({backdrop: 'static', keyboard: false});
                                        $('#nogoodModel').modal('show');
                                    }
                                }else{     
                                    $('#trainModel').modal('hide');       // 隐藏模态框
                                    if (res.data){
                                        stock_data = JSON.parse(res.data); 
                                        recent_data = stock_data.recent_data;
                                        predict_data = stock_data.predict_data;
                                        stock_code = stock_data.stock_code;
                                        stock_name = stock_data.stock_name;
                                    }
                                }
                                
                                if(recent_data != null && predict_data != null && stock_code != null && stock_name != null){
                                    draw_chart();
                                }
    
                                if(indexs != null){
                                    draw_radar();
                                }
                            }
                            
                        },
                        error: function (msg) {
                            alert(JSON.stringify(msg));
                        }
                    });
                }          
                return false;    
            });
        });
    </script>
{% endblock %}
{% block nav %}
<li class="active">
    <a href="/boards/" class="btn btn-success" style='float:right;margin:10px'>
        返回
    </a>
</li>
{% endblock nav %}
{% block content %}
<div class="content">
    <img alt="" height="180" src="{% static 'prediction/img/mediadem_polls_LauraLalonde.gif' %}" width="500"/>
    <div class="form-group col-sm-6 col-sm-offset-1">
        <h4 style="color:red">股票选项预测</h4>
        <form align="left"  id="myform">
            {% csrf_token %}
            <div id="id_option" class="inline">
                <label for="id_option_1">
                    <input type="radio" name="option" id="id_option_1" value="1" class="inline" required> 短期趋势预测
                </label>
                <label for="id_option_2" style= "margin-left: 20px">
                    <input type="radio" name="option" id="id_option_2" value="2" class="inline" required> 次日最高价与最低价预测
                </label>
            </div>
            {{ form.as_p }}
            <div><button type="submit" class="btn btn-success" >执行</button> 
            <div class="checkbox" style="float : right; margin-right: 50px" class="inline">
                <label>
                  <input type="checkbox" name="again" class="inline">
                    再学习训练一次
                </label>
                <label style="margin-left: 20px">
                    <input type="checkbox" name="good" class="inline">
                      使用训练好的模型预测
                  </label>
            </div>
            
        </form>
    </div> 
</div>
<center>
    <!-- 为ECharts准备一个具备大小（宽高）的容器 -->
    <div style="width:100%;height:400px;margin-top:50px;">
        <div id="hist_futu" style="float:left;width: 100%;height:450px;"></div>
        <div id="radar" style="width:50%;height:600px;"></div>
    </div>
</center>
<div class="modal fade" id="trainModel">
    <div class="modal-dialog">
        <div class="modal-content message_align" style="width:400px;height:80px;margin-top:220px;margin-left:130px">
            <div class="modal-header" style="text-align:left;font-size:small;height:8px;margin-bottom:10px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top:-15px"><span
                    aria-hidden="true">×</span></button>
                <h5 class="modal-title" style="margin-top:-10px;color:dodgerblue">人工智能深度机器学习</h5>
            </div>
            <div class="modal-body" style="text-align: center;font-size:16px;height: 18px;color:chocolate">
                <p style="margin-top:-15px">正在训练数据中，请耐心等待......</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success">训练结束将关闭</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="preModel">
    <div class="modal-dialog">
        <div class="modal-content" style="width:400px;height:80px;margin-top:220px;margin-left:130px">
            <div class="modal-header" style="text-align:left;font-size:small;height:8px;margin-bottom:10px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top:-15px"><span
                    aria-hidden="true">×</span></button>
                <p class="modal-title" style="margin-top:-10px;color:dodgerblue">人工智能预测</p>
            </div>
            <div class="modal-body" style="text-align: center;font-size:16px;height: 18px;color:chocolate">
                <p style="margin-top:-15px">正在获取模型预测中，请耐心等待......</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success">预测结束将关闭</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="bothModel">
    <div class="modal-dialog">
        <div class="modal-content message_align" style="width:400px;height:80px;margin-top:220px;margin-left:130px">
            <div class="modal-header" style="text-align:left;font-size:small;height:8px;margin-bottom:10px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top:-15px"><span
                        aria-hidden="true">×</span></button>
                <h5 class="modal-title" style="margin-top:-10px;color:dodgerblue">只能选一个！</h5>
            </div>
            <div class="modal-body" style="text-align: center;font-size:16px;height: 18px;color:chocolate">
                <p style="margin-top:-15px">"再学习训练一次" 与 "使用训练好的模型预测" 只能选一个</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="nogoodModel">
    <div class="modal-dialog">
        <div class="modal-content message_align" style="width:400px;height:80px;margin-top:220px;margin-left:130px">
            <div class="modal-header" style="text-align:left;font-size:small;height:8px;margin-bottom:10px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top:-15px"><span
                        aria-hidden="true">×</span></button>
                <h5 class="modal-title" style="margin-top:-10px;color:dodgerblue">没有训练好的模型！</h5>
            </div>
            <div class="modal-body" style="text-align: center;font-size:16px;height: 18px;color:chocolate">
                <p style="margin-top:-15px">暂时没有学习训练好的模型，请继续训练......</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock content %}